# Generated by Django 2.2 on 2019-04-28 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWillApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentdemande',
            old_name='DCRCODE',
            new_name='DCRID',
        ),
        migrations.AddField(
            model_name='documentdemande',
            name='DEMID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamWillApp.DEMANDECREDIT'),
        ),
        migrations.AddField(
            model_name='documentdemande',
            name='DocumentFile',
            field=models.FileField(null=True, upload_to='./demande'),
        ),
    ]
