# Generated by Django 2.2 on 2019-04-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWillApp', '0002_auto_20190428_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecredit',
            name='COMMENTAIREAGENT',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='ETATACCEPTATION',
            field=models.CharField(default='En Attente', max_length=50),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='ETATDOCUMENT',
            field=models.CharField(default='En Attente', max_length=50),
        ),
    ]
