# Generated by Django 2.2 on 2019-04-28 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWillApp', '0003_auto_20190428_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierprospect',
            name='TCID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamWillApp.TypeCredit'),
        ),
        migrations.AlterField(
            model_name='demandecredit',
            name='COMMENTAIREAGENT',
            field=models.CharField(default='En Attente', max_length=255),
        ),
    ]
