# Generated by Django 2.2 on 2019-04-28 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWillApp', '0004_auto_20190428_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecredit',
            name='TCID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamWillApp.TypeCredit'),
        ),
    ]
