# Generated by Django 2.2 on 2019-04-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWillApp', '0005_demandecredit_tcid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOSECHEANCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOSID', models.IntegerField()),
                ('ORDRE', models.IntegerField()),
                ('DATEECHEANCE', models.DateField()),
                ('MONTANTECHEANCE', models.IntegerField()),
                ('DATEPAIEMENT', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
