# Generated by Django 2.2 on 2019-04-28 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWillApp', '0007_auto_20190428_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='PROID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamWillApp.PROSPECT'),
        ),
        migrations.AlterField(
            model_name='dosecheance',
            name='DOSID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamWillApp.DOSSIER'),
        ),
    ]
