# Generated by Django 2.2 on 2019-04-28 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TeamWillApp', '0008_auto_20190428_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
