# Generated by Django 2.2 on 2019-04-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWillApp', '0009_prospect_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='PRODATENAISS',
            field=models.DateField(null=True),
        ),
    ]
