# Generated by Django 2.2 on 2019-04-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWillApp', '0010_auto_20190428_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='PROMAIL',
            field=models.CharField(max_length=100),
        ),
    ]
