# Generated by Django 2.2 on 2019-04-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWillApp', '0011_auto_20190428_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierprospect',
            name='DPRDATEPROCPECT',
            field=models.DateField(null=True),
        ),
    ]
