# Generated by Django 2.2 on 2019-04-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWillApp', '0012_dossierprospect_dprdateprocpect'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecredit',
            name='DATE',
            field=models.DateField(null=True),
        ),
    ]
