# Generated by Django 2.2 on 2019-04-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWillApp', '0013_demandecredit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='typecredit',
            name='TCRIMAGE',
            field=models.CharField(default='', max_length=40),
        ),
    ]
